config/routes.rb
Rails.application.routes.draw do
  devise_for :users 

  get '/vote', to: 'users#vote', as: :vote
  get '/veto', to: 'users#veto', as: :veto
  post '/suggestion', to: 'users#suggestion', as: :suggestion
  root to: 'home#index'
  get '/search', to: 'home#spotify_search', as: :spotify_search
  get '/spotify_oauth', to: 'users#spotify_oauth', as: 'spotify_oauth'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end

  def spotify_search
    @search_results = []
    if search_params
      tracks = RSpotify::Track.search(search_params, limit: 25)
      # artists = RSpotify::Artist.search(search_params, limit: 10)
      # playlists = RSpotify::Playlist.search('Indie')
      # albums = RSpotify::Album.search('The Wall')
      @query = search_params
      @count = tracks.total
      @search_results = tracks
    end

    render :show
  end

  def show

  end


  private

  def search_params
    params[:search_query]
  end

end

app/helpers/home_helper.rb
module HomeHelper
  
  def song_list
    Song.all.order([:votes].count)
  end

end

app/views/home/index.html.erb
<%= render partial: "shared/flash_messages", flash: flash %> 

<div class="jumbotron jumboSections">
    <div class="form-group form-inline searchWrap"> <!-- start searchBar --> <div>
        <%= form_tag spotify_search_path, method: 'get' do %>
        <%= text_field_tag 'search_query', 
                      params[:search_query], 
                      :class => "form-control input-lg searchBox",
                      :placeholder => 'Find a song and Spotify ME' %> 
    </div>
    <div>      
          <%= button_tag(type: "submit", class: "btn btn-primary btn-lg searchButton") do %>
            Search <i class="fa fa-sign-out" style="margin-left: 10px;"></i>
          <% end %>        
        <% end %> 
    </div>
</div>
     <!-- end searchBar -->
  <% spotify_link = 'https://accounts.spotify.com/authorize?' +
       { client_id: ENV['SPOTIFY_CLIENT_ID'],
         redirect_uri: 'localhost:3000/spotify_oauth',
         response_type: 'code', 
         scope: 'playlist-modify-public playlist-modify-private user-follow-modify'}.to_query %>
  <%= link_to "spotify", spotify_link %>
</div>


<div class="row center-block songRankings">
  <!--<#% @playlist.current_week.each do |song|%> -->
  <h2>Top songs</h2>
  <h4>(current_week)</h4>


  <div class="col-xs-12 center-block">
    <% song_list.each do |song|%>
    <ul class="list-group">
      <h4 class="panel panel-default oneSpot"> 
        <%= song.title %> by <%= song.artist %>
        <h3><%= link_to 'vote', vote_path(song_id: song.id) %><%= song.votes.count %> | <%= link_to 'veto', veto_path(song_id: song.id) %><%= song.veto_count %></h3>
        
      </h4>
    </ul>
    <% end %>
  </div>
</div>


<div class="jumbotron jumboSections">
  
</div>

app/views/home/show.html.erb
<h2 style='margin-top: 150px;'>songs</h2>

<h4>search results for <span>"<%= @query %>"</span></h4>

  <ul>
  <% @search_results.each do |song| %>
    <li>
    
        <h3>song: <%= song.name %>,
            artist: <%= song.artists.first.name %>,
        <!-- images_urls: <#%= song.images %>, -->
        spotify popularity <%= song.popularity %></h3>

      <div class="submitSong">
        <%= form_tag suggestion_path(pick: song.id), method: 'post', remote: true %>
        <%= submit_tag 'suggest song', :class => "btn btn-primary btn-lg" %>
      </div>
    </li>
    <% end %>
  </ul>



  <h5><%= @count %> total tracks <%= @query %></h5>